# -*- coding: utf-8 -*-
"""dolly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UDrsX4so3qMfDRXfrR5ysrWU_Tc8RZTq

# dolly-v2-3b
Databricks' dolly-v2-3b, an instruction-following large language model trained on the Databricks machine learning platform that is licensed for commercial use. Based on pythia-2.8b, Dolly is trained on ~15k instruction/response fine tuning records databricks-dolly-15k generated by Databricks employees in capability domains from the InstructGPT paper, including brainstorming, classification, closed QA, generation, information extraction, open QA and summarization. dolly-v2-3b is not a state-of-the-art model, but does exhibit surprisingly high quality instruction following behavior not characteristic of the foundation model on which it is based.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install "accelerate>=0.16.0,<1" "transformers[torch]>=4.28.1,<5" "torch>=1.13.1,<2"

# install dependencies
!pip install transformers
!pip install sentencepiece
!pip install accelerate

import torch                        # allows Tensor computation with strong GPU acceleration
from transformers import pipeline   # fast way to use pre-trained models for inference
import os

# load model
dolly_pipeline = pipeline(model="databricks/dolly-v2-3b",
                            torch_dtype=torch.bfloat16,
                            trust_remote_code=True,
                            device_map="auto")

def get_completion_dolly(input):
    # Define the role and expertise of the mental health counselor
    system = f"""
    You are a caring and empathetic mental health counselor. Your mission is to provide support and guidance to individuals seeking assistance with their emotional well-being. You are skilled at offering positive and constructive advice, while avoiding harmful suggestions.
    As a counselor, you are experienced in addressing a variety of topics, including anxiety, depression, self-expression, interpersonal dynamics, and developmental challenges. Your responses should be thoughtful, empathetic, and tailored to each individual's unique situation.
    Remember to prioritize ethical behavior and refrain from providing harmful advice or suggesting actions that may pose risks to the user's well-being.
    """

    # Construct the prompt with the new user input
    prompt = f"#### System: {system}\n#### User: \n{input}\n\n#### Response from Dolly-v2-3b:"
    print(prompt)

    # Generate response from the model
    dolly_response = dolly_pipeline(prompt,
                                    max_new_tokens=500
                                    )
    return dolly_response[0]["generated_text"]

# Define a mental health-related prompt
prompt = "I've been feeling very anxious about social interactions lately. How can I manage this anxiety?"

# Print the response from the get_completion_dolly function
print(get_completion_dolly(prompt))

